version: '3.7'
services:
    booking_microservice_postgres:
        container_name: booking_microservice_postgres
        image: postgres:11.9
        environment:
          - POSTGRES_USER=booking_microservice
          - POSTGRES_PASSWORD=booking_microservice
          - POSTGRES_DB=booking_microservice
          - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
          - 54321:5432
        volumes:
          - /var/lib/postgresql/data/pgdata
        logging:
            options:
                max-size: 10m
                max-file: "3"
    booking_microservice_api:
      container_name: booking_microservice_api
      depends_on:
        - postgres
      build:
        context: ../
        dockerfile: Dockerfile
      ports:
        - "5000:5000"
      environment:
        - DATABASE_URL=postgres://booking_microservice:booking_microservice@postgres/booking_microservice
      entrypoint: /app/docker-compose/api-entrypoint.sh
