"""refactor model

Revision ID: 069d53cf594f
Revises: a96132adcf5f
Create Date: 2020-12-13 12:11:47.388482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '069d53cf594f'
down_revision = 'a96132adcf5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("booking") as batch_op:
        batch_op.alter_column("booking_id", new_column_name="id")
        batch_op.alter_column(
            "room_id", new_column_name="publication_id", nullable=False
        )
        batch_op.alter_column("final_date", nullable=False)
        batch_op.alter_column("initial_date", nullable=False)
        batch_op.alter_column("tenant_id", nullable=False)
        batch_op.alter_column("total_price", nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("booking") as batch_op:
        batch_op.alter_column("id", new_column_name="booking_id")
        batch_op.alter_column(
            "publication_id", new_column_name="room_id", nullable=True
        )
        batch_op.alter_column("final_date", nullable=True)
        batch_op.alter_column("initial_date", nullable=True)
        batch_op.alter_column("tenant_id", nullable=True)
        batch_op.alter_column("total_price", nullable=True)
