"""booking_status

Revision ID: 7eb209b7ab1e
Revises: 0a95c6679356
Create Date: 2021-02-22 01:19:10.744915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from booking_microservice.constants import BookingStatus

# revision identifiers, used by Alembic.
revision = '7eb209b7ab1e'
down_revision = '0a95c6679356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    connection = op.get_bind()
    if connection.dialect.name == "postgresql":
        status_enum = postgresql.ENUM(
            *[x.value for x in BookingStatus.__members__.values()],
            name='booking_status'
        )
    else:
        status_enum = sa.Enum(
            *[x.value for x in BookingStatus.__members__.values()],
            name='booking_status'
        )

    status_enum.create(op.get_bind())

    op.add_column(
        'booking',
        sa.Column(
            'booking_status',
            status_enum,
            nullable=False,
            default=BookingStatus.PENDING.value,
            server_default=BookingStatus.PENDING.value,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'booking_status')
    # ### end Alembic commands ###
