"""fix dates

Revision ID: b73363ca9f31
Revises: 069d53cf594f
Create Date: 2020-12-13 12:53:43.610801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b73363ca9f31'
down_revision = '069d53cf594f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("booking") as batch_op:
        batch_op.alter_column(
            'final_date',
            existing_type=sa.DATETIME(),
            type_=sa.Date(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            'initial_date',
            existing_type=sa.DATETIME(),
            type_=sa.Date(),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("booking") as batch_op:
        batch_op.alter_column(
            'initial_date',
            existing_type=sa.Date(),
            type_=sa.DATETIME(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            'final_date',
            existing_type=sa.Date(),
            type_=sa.DATETIME(),
            existing_nullable=False,
        )
    # ### end Alembic commands ###
