"""add booking date

Revision ID: b7e66d9d30da
Revises: b73363ca9f31
Create Date: 2020-12-13 13:10:47.812954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e66d9d30da'
down_revision = 'b73363ca9f31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('booking_date', sa.DateTime(), nullable=True))
    op.execute("UPDATE booking SET booking_date = 'now()'")
    with op.batch_alter_table("booking") as batch_op:
        batch_op.alter_column("booking_date", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'booking_date')
    # ### end Alembic commands ###
